"""add_bank_offer_condition_fields

Revision ID: 129f08f7683e
Revises: f2ed59b699de
Create Date: 2025-12-06 02:22:22.125159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '129f08f7683e'
down_revision: Union[str, Sequence[str], None] = 'f2ed59b699de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_offers', sa.Column('min_credit_score', sa.Integer(), nullable=True))
    op.add_column('bank_offers', sa.Column('max_days_past_due', sa.Integer(), nullable=True))
    op.add_column('bank_offers', sa.Column('conditions_description', sa.String(length=500), nullable=True))
    op.drop_column('bank_offers', 'conditions')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_offers', sa.Column('conditions', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('bank_offers', 'conditions_description')
    op.drop_column('bank_offers', 'max_days_past_due')
    op.drop_column('bank_offers', 'min_credit_score')
    # ### end Alembic commands ###
