"""init_entities

Revision ID: f2ed59b699de
Revises: 
Create Date: 2025-12-06 01:32:47.598903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2ed59b699de'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_offers',
    sa.Column('offer_id', sa.String(length=50), nullable=False),
    sa.Column('product_types_eligible', postgresql.ARRAY(sa.String(length=20)), nullable=False),
    sa.Column('max_consolidated_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('new_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('max_term_months', sa.Integer(), nullable=False),
    sa.Column('conditions', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bank_offers_offer_id'), 'bank_offers', ['offer_id'], unique=True)
    op.create_table('customers',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('monthly_income_avg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('income_variability_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('essential_expenses_avg', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_external_id'), 'customers', ['external_id'], unique=True)
    op.create_table('credit_score_history',
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('score_date', sa.Date(), nullable=False),
    sa.Column('credit_score', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_score_history_customer_id'), 'credit_score_history', ['customer_id'], unique=False)
    op.create_index(op.f('ix_credit_score_history_score_date'), 'credit_score_history', ['score_date'], unique=False)
    op.create_table('products',
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('product_type', sa.String(length=20), nullable=False),
    sa.Column('annual_rate_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_products_customer_id'), 'products', ['customer_id'], unique=False)
    op.create_index(op.f('ix_products_external_id'), 'products', ['external_id'], unique=True)
    op.create_table('cards',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('min_payment_pct', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('payment_due_day', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loans',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('loan_type', sa.String(length=20), nullable=False, comment='personal or micro'),
    sa.Column('principal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('remaining_term_months', sa.Integer(), nullable=False),
    sa.Column('collateral', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('product_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('customer_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_payment_date'), 'payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_payments_product_id'), 'payments', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_product_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_date'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_table('loans')
    op.drop_table('cards')
    op.drop_index(op.f('ix_products_external_id'), table_name='products')
    op.drop_index(op.f('ix_products_customer_id'), table_name='products')
    op.drop_table('products')
    op.drop_index(op.f('ix_credit_score_history_score_date'), table_name='credit_score_history')
    op.drop_index(op.f('ix_credit_score_history_customer_id'), table_name='credit_score_history')
    op.drop_table('credit_score_history')
    op.drop_index(op.f('ix_customers_external_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_bank_offers_offer_id'), table_name='bank_offers')
    op.drop_table('bank_offers')
    # ### end Alembic commands ###
